Closes #266, Icinga notification template imports bug
telekom-mms/ansible-collection-icinga-director pull request #267
Opened 2024-11-17 16:36 UTC by gianmarco-mameli

Closes #266, Icinga notification template imports bug 
Let me know if it's ok, I already tried on my Icinga install

2024-11-18 10:51 UTC, gianmarco-mameli commented
Yes, of course. The run give me errors with YQ `Error: unknown shorthand flag: 'a' in -a=append`.
I'm on MacOS Arm64, yq installed via Brew version 4.44.5, maybe it's too recent?

2024-11-19 08:57 UTC, schurzi commented
@gianmarco-mameli that changes from #269 are merged now, can you please rebase and fix the linting errors. If you want to try you can also try to update the tests. For this you need to use yq in version 3.4.1, nothing else will work at the moment.

2024-11-19 16:37 UTC, gianmarco-mameli commented
I installed the yq version 3.4.1 on a debian container, because via Brew on mac it's only available the latest version.
I launched the script but I think something is not right:
I received an error and 5 files modified, but all empty (only the yaml `---` on top)

![Screenshot 2024-11-19 at 17 35 44](https://github.com/user-attachments/assets/7553b0b5-0a0e-4b5a-91c3-e02d344de4b9)
![Screenshot 2024-11-19 at 17 35 53](https://github.com/user-attachments/assets/a5d0c015-fdae-44aa-9de1-e7a55000bb9b)

2024-11-19 16:56 UTC, schurzi commented
nice! The errors you get are actually expected, because you have some minor problems with the code. ;)
see: https://github.com/telekom-mms/ansible-collection-icinga-director/actions/runs/11880503521/job/33129443662#step:3:987

2024-11-19 16:58 UTC, schurzi requested changes

2024-11-19 16:58 UTC, schurzi commented on plugins/modules/icinga_notification_template.py
> +  imports:
this is messing keys for `type` and `elements`

2024-11-19 16:58 UTC, schurzi commented on plugins/modules/icinga_notification_template.py
> +        imports:
the indentation is wrong.

2024-11-19 17:21 UTC, gianmarco-mameli commented
My bad sorry! Now seems to be ok, thanks for the support

2024-11-19 17:38 UTC, schurzi commented
> My bad sorry! 

No worries! In the end this is what tests are for. ;)

Now we have a problem with our tests. you added the import for `footemplate`in the task that adds `footemplate` this is not deployable :D

The easy solution might be to leave the added `imports` out of the example. This way it will only be shown in docs, which should be enoug.

2024-11-19 17:58 UTC, gianmarco-mameli commented
yep, I see the errors. I'm going to fix it now

2024-11-19 19:35 UTC, gianmarco-mameli commented
yeah, checks passed

2024-11-19 22:44 UTC, schurzi approved these changes

2024-11-19 22:44 UTC, merged

2024-11-19 22:44 UTC, schurzi commented
Thank you! It was a nice experience working with you on that.